import type { Metadata } from "next";
import Link from "next/link";
import "../legal/legal.css";

export const metadata: Metadata = {
  title: "Política de Tratamiento de Datos | Brilla",
  description: "Política de tratamiento de datos personales de Brilla, operada por TECNOLOGYC S.A.S.",
};

const privacyEmail = "abner.chamorro@brillaugc.com";

export default function PrivacyPolicyPage() {
  return <main className="legalPage">
    <nav className="legalNav"><Link className="legalBrand" href="/">brilla<span>•</span></Link><Link href="/cuenta">Volver a mi cuenta</Link></nav>
    <header className="legalHero"><span>VERSIÓN 6 DE SEPTIEMBRE DE 2026</span><h1>Política de Tratamiento de Datos Personales</h1><p>Esta política explica qué información trata Brilla, para qué la utiliza, con quién puede compartirla y cómo puede ejercer sus derechos cada titular.</p></header>
    <div className="legalLayout">
      <aside className="legalSummary"><strong>Responsable del tratamiento</strong><span>TECNOLOGYC S.A.S.<br />NIT 901787723-2<br />Calle 159 #56-75, Torre 1, apto. 1101<br />Bogotá D.C., Colombia<br />Tel. 320 318 5347</span><a href={`mailto:${privacyEmail}`}>{privacyEmail}</a></aside>
      <article className="legalContent">
        <section><h2>1. Objeto y alcance</h2><p>TECNOLOGYC S.A.S., responsable de la plataforma Brilla, adopta esta Política de Tratamiento de Datos Personales en cumplimiento de la Constitución Política de Colombia, la Ley 1581 de 2012, el Decreto 1377 de 2013 incorporado en el Decreto 1074 de 2015 y las normas que los modifiquen o complementen. Se aplica a la información de creadoras, visitantes, contactos y demás personas naturales cuyos datos sean tratados a través de Brilla.</p></section>
        <section><h2>2. Datos que tratamos</h2><ul><li><strong>Cuenta e identidad:</strong> nombre, correo, foto de perfil, identificadores de autenticación y datos básicos entregados por Google al iniciar sesión.</li><li><strong>Portafolio:</strong> nombre público, biografía, ubicación, nichos, piezas, fotos, videos, logos, tarifas, audiencia declarada, redes sociales y medios de contacto que la creadora decida agregar.</li><li><strong>Publicación:</strong> enlace público, estado, plantilla, contenido visible y fechas de actualización.</li><li><strong>Actividad:</strong> visitas aproximadas y clics de contacto asociados a un identificador aleatorio del navegador. Brilla no almacena la dirección IP dentro del historial de eventos del portafolio.</li><li><strong>Comunicaciones:</strong> preferencias, métricas agregadas y registros necesarios para enviar bienvenida, confirmación de publicación y resúmenes solicitados.</li><li><strong>Prueba de autorización:</strong> identidad de la cuenta, versión de los documentos, texto autorizado, medio y fecha de aceptación.</li><li><strong>Datos técnicos:</strong> información de sesión, seguridad, errores y almacenamiento local estrictamente necesaria para operar y proteger el servicio.</li></ul><div className="legalCallout"><p>Brilla no solicita datos sensibles ni información de niñas, niños o adolescentes. Evite subir información sensible o datos de terceros sin contar con autorización.</p></div></section>
        <section><h2>3. Finalidades</h2><p>Los datos serán tratados para:</p><ol><li>Crear, autenticar y proteger la cuenta mediante Google y Supabase.</li><li>Guardar, editar, respaldar, convertir y mostrar el portafolio y su media kit PDF.</li><li>Publicar y compartir el contenido que la creadora marque como público.</li><li>Gestionar archivos, enlaces, preferencias, solicitudes y soporte.</li><li>Medir visitas y clics de forma aproximada, prevenir abuso y mostrar métricas agregadas.</li><li>Enviar comunicaciones esenciales y los resúmenes de actividad que la creadora active.</li><li>Mantener seguridad, disponibilidad, diagnóstico, trazabilidad y cumplimiento legal.</li><li>Atender consultas, reclamos, solicitudes de acceso, actualización, corrección, supresión y revocación.</li></ol><p>Brilla no venderá datos personales ni usará la autorización obligatoria de acceso para publicidad de terceros. Cualquier comunicación comercial opcional requerirá un consentimiento separado.</p></section>
        <section><h2>4. Publicación y circulación</h2><p>El portafolio permanece privado mientras sea borrador o esté despublicado. Al publicarlo, la creadora ordena mostrar en Internet el contenido, archivos y medios de contacto seleccionados. Puede despublicarlo desde su cuenta. Los datos podrán entregarse al titular, a sus representantes, a autoridades competentes o a terceros autorizados por el titular o por la ley.</p></section>
        <section><h2>5. Encargados y transmisión internacional</h2><p>Para operar Brilla, TECNOLOGYC S.A.S. utiliza proveedores tecnológicos que pueden tratar datos por su cuenta y bajo sus instrucciones, incluso desde otros países:</p><ul><li><strong>Supabase:</strong> autenticación, base de datos, almacenamiento, funciones y tareas programadas.</li><li><strong>Vercel:</strong> alojamiento y entrega de la aplicación web.</li><li><strong>Resend:</strong> envío de correos autorizados y métricas técnicas de entrega.</li><li><strong>Google:</strong> autenticación OAuth; Google también trata información conforme a sus propios términos y políticas.</li></ul><p>TECNOLOGYC S.A.S. limitará estas transmisiones a lo necesario para prestar el servicio y exigirá medidas de confidencialidad y seguridad aplicables.</p></section>
        <section><h2>6. Derechos de los titulares</h2><p>El titular puede conocer, acceder gratuitamente, actualizar y rectificar sus datos; solicitar prueba de la autorización; conocer el uso dado a su información; presentar consultas y reclamos; solicitar la supresión o revocar la autorización cuando proceda; y presentar quejas ante la Superintendencia de Industria y Comercio después de agotar el trámite ante TECNOLOGYC S.A.S.</p></section>
        <section><h2>7. Consultas y reclamos</h2><p>Las solicitudes deben enviarse a <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a> e incluir nombre, identificación suficiente para validar al titular, descripción clara de la solicitud, medio de respuesta y documentos de soporte cuando correspondan.</p><p>Las consultas serán atendidas en un máximo de diez (10) días hábiles, prorrogables por cinco (5) días hábiles cuando sea necesario y se informe oportunamente. Los reclamos serán atendidos en un máximo de quince (15) días hábiles, prorrogables por ocho (8) días hábiles bajo las condiciones legales.</p></section>
        <section><h2>8. Seguridad y conservación</h2><p>Brilla aplica controles de acceso, políticas por usuario, almacenamiento privado, enlaces temporales, validación de archivos y separación de datos internos. Ningún sistema es infalible; ante un incidente se aplicarán las medidas de contención, investigación y notificación exigibles.</p><p>La información se conservará mientras la cuenta o el portafolio estén activos y durante el tiempo adicional necesario para cumplir obligaciones legales, resolver controversias y demostrar autorizaciones. Los datos se eliminarán o anonimizarán cuando dejen de ser necesarios, salvo deber legal de conservación.</p></section>
        <section><h2>9. Revocación, supresión y cierre</h2><p>La creadora puede despublicar o eliminar su portafolio desde su cuenta. Para revocar la autorización, solicitar supresión integral o cerrar la cuenta de autenticación debe escribir al canal de privacidad. La revocación no afecta tratamientos realizados válidamente antes de la solicitud ni la conservación exigida por ley.</p></section>
        <section><h2>10. Cambios y vigencia</h2><p>Esta política rige desde el 6 de septiembre de 2026. Los cambios sustanciales en la identidad del responsable o en las finalidades se informarán antes de entrar en vigor y, cuando corresponda, se solicitará una nueva autorización. Las bases de datos permanecerán vigentes mientras Brilla opere y subsistan las finalidades o deberes legales aquí descritos.</p></section>
      </article>
    </div>
    <footer className="legalFooter"><span>© 2026 TECNOLOGYC S.A.S. · Brilla UGC</span><div><Link href="/privacidad">Política de datos</Link><Link href="/terminos">Términos de uso</Link><a href={`mailto:${privacyEmail}`}>Contacto de privacidad</a></div></footer>
  </main>;
}
