"use client";

import { Icon } from "../components/brilla-icon";


/* User media uses local blob URLs and private signed URLs. */
/* eslint-disable @next/next/no-img-element */

import { CSSProperties } from "react";
import type { BrandAsset, CaseStudy, Media, Portfolio, TemplateSchema } from "./page";
import { portfolioOption, portfolioOptions, portfolioText } from "./portfolio-i18n";

type ExperienceProps = {
  data: Portfolio;
  media: Media[];
  brands: BrandAsset[];
  schema: TemplateSchema;
  expanded: boolean;
};

function emailLink(value: string) { return `mailto:${value.trim()}`; }
function whatsappLink(value: string) { return `https://wa.me/${value.replace(/\D/g, "")}`; }
function socialLink(network: "instagram" | "tiktok", value: string) {
  const trimmed = value.trim();
  if (/^https?:\/\//i.test(trimmed)) return trimmed;
  return `https://${network}.com/${trimmed.replace(/^@/, "")}`;
}
function hasText(value: string) { return value.trim().length > 0; }
function hasAnyText(...values: string[]) { return values.some(hasText); }
function portfolioAccent(data: Portfolio) { return data.accent || "#6d4dff"; }
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "UGC"; }
function visibleWork(data: Portfolio, media: Media[]) { return media.filter((item) => data.portfolioCategories.includes(item.category)); }
function categoryGroups(data: Portfolio, media: Media[], schema: TemplateSchema) {
  const work = visibleWork(data, media);
  return data.portfolioCategories.map((category) => ({
    category,
    items: work.filter((item) => item.category === category).slice(0, category === "Fotografía" ? schema.photoLimit : schema.categoryLimit),
  })).filter((group) => group.items.length);
}
function servicePrice(data: Portfolio, service: string) {
  const normalized = service.toLowerCase();
  if (normalized.includes("reel")) return data.collabRate;
  if (normalized.includes("pack") && normalized.includes("historia")) return data.storyPackRate;
  if (normalized.includes("historia")) return data.storyRate;
  if (normalized.includes("pauta") || normalized.includes("ads")) return data.usageRate;
  if (normalized.includes("video")) return data.videoRate;
  return portfolioText(data, "Cotización personalizada", "Custom quote");
}

function ExperienceMedia({ item, label, ambient = false, priority = false }: { item: Media | null; label: string; ambient?: boolean; priority?: boolean }) {
  return <div className={`experienceMedia ${item?.type === "video" ? "isVideo" : "isImage"}`}>
    {item ? item.type === "video"
      ? <video src={item.url} poster={item.previewUrl} muted playsInline controls={!ambient} autoPlay={ambient} loop={ambient} preload={ambient ? "auto" : "metadata"} aria-label={`Video UGC de ${label}`} />
      : <img src={item.url} alt={`Pieza UGC de ${label}`} loading={priority ? "eager" : "lazy"} />
      : <div className="experiencePlaceholder"><span>{label}</span><b>UGC</b><i><Icon glyph="▶" /></i></div>}
    {item && (item.instagram || item.tiktok) && <div className="experienceSocials">{item.instagram && <a href={item.instagram} target="_blank" rel="noreferrer" aria-label="Ver pieza en Instagram" data-analytics-target="instagram">IG</a>}{item.tiktok && <a href={item.tiktok} target="_blank" rel="noreferrer" aria-label="Ver pieza en TikTok" data-analytics-target="tiktok">TK</a>}</div>}
  </div>;
}

const emptyCase: CaseStudy = { client: "", brief: "", hook: "", result: "", testimonial: "" };

export function CreatorFeedPortfolio({ data, media, brands, schema, expanded }: ExperienceProps) {
  const portrait = media.find((item) => item.category === "__portrait") ?? null;
  const work = visibleWork(data, media);
  const pinned = Array.from({ length: 3 }, (_, index) => work[index] ?? null);
  const pinnedIds = new Set(pinned.flatMap((item) => item ? [item.id] : []));
  const groups = categoryGroups(data, media.filter((item) => !pinnedIds.has(item.id)), schema);
  const countries = data.topCountries.split("·").map((item) => item.trim()).filter(Boolean);
  const handle = data.instagram.trim() || data.tiktok.trim() || `@${data.name.toLowerCase().replace(/[^a-z0-9]+/g, "")}`;
  return <div className={`creatorFeed font-${data.fontStyle} ${expanded ? "expanded" : "compact"}`} style={{ "--site-accent": portfolioAccent(data), "--experience-accent": portfolioAccent(data) } as CSSProperties}>
    <header className="feedNav"><a className="feedIdentity" href="#feed-top"><span className="feedAvatar">{initials(data.name)}</span><span>{hasText(data.name) && <strong>{data.name}</strong>}{hasText(data.location) && <small>UGC creator · {data.location}</small>}</span></a><nav>{work.length > 0 && <a href="#feed-work">{portfolioText(data, "Contenido", "Content")}</a>}{hasText(data.bio) && <a href="#feed-story">{portfolioText(data, "Sobre mí", "About me")}</a>}{data.services.length > 0 && <a href="#feed-services">{portfolioText(data, "Servicios", "Services")}</a>}</nav>{hasText(data.whatsapp) && <a className="feedNavCta" href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Trabajemos ↗", "Let's work ↗")}</a>}</header>
    <section className="feedHero" id="feed-top"><div className="feedHeroCopy"><span className="feedStatus"><i />{data.availability}</span><h1><span>{portfolioText(data, "Contenido que", "Content that")}</span><em>{portfolioText(data, "se siente real.", "feels real.")}</em></h1><p className="feedHeroLead">{data.bio}</p><div className="feedHeroTags">{data.niches.map((niche) => <span key={niche}>#{portfolioOption(data, niche).toLowerCase()}</span>)}</div><div className="feedHeroActions"><a href="#feed-work">{portfolioText(data, "Ver mis elegidos ↓", "View my picks ↓")}</a><div className="feedSocialLinks">{hasText(data.instagram) && <a href={socialLink("instagram", data.instagram)} data-analytics-target="instagram">IG</a>}{hasText(data.tiktok) && <a href={socialLink("tiktok", data.tiktok)} data-analytics-target="tiktok">TK</a>}</div></div></div><div className="feedProfileVisual"><div className="feedPhone"><ExperienceMedia item={portrait} label={portfolioText(data, "Retrato principal", "Main portrait")} priority /></div><div className="feedProfileBadge"><span><Icon glyph="✦" /></span><div><b>{handle}</b><small>{data.title}</small></div></div></div></section>
    {work.length > 0 && <section className="feedPinned feedSection" id="feed-work"><div className="feedSectionHeader"><div><small className="feedKicker">{portfolioText(data, "MIS FIJADOS", "PINNED")}</small><h2>{portfolioText(data, "Tres piezas para conocer mi estilo.", "Three pieces to discover my style.")}</h2></div><p>{portfolioText(data, "Ideas de marca convertidas en contenido que la gente sí quiere ver.", "Brand ideas turned into content people actually want to watch.")}</p></div><div className="feedPinnedGrid">{pinned.filter(Boolean).map((item, index) => <article className="feedPost" key={item?.id ?? `feed-${index}`}><span className="feedPinLabel"><Icon glyph="✦" /> {portfolioText(data, "FIJADO", "PINNED")}</span><div className="feedPinnedMedia"><ExperienceMedia item={item} label={portfolioOption(data, item?.category ?? data.niches[index] ?? "UGC")} /></div><div className="feedPostMeta"><strong>{portfolioOption(data, item?.category ?? "UGC")}</strong><small>{portfolioOption(data, data.contentTypes[index % Math.max(1, data.contentTypes.length)] ?? "UGC")}</small><span><Icon glyph="▶" /></span></div></article>)}</div></section>}
    {(hasText(data.bio) || data.contentTypes.length > 0 || hasAnyText(data.followers, data.monthlyViews, data.womenAudience)) && <section className="feedStory feedSection" id="feed-story"><div className="feedStoryCopy"><span className="feedStoryLabel">{portfolioText(data, "MI MANERA DE CREAR", "HOW I CREATE")}</span><h2>{portfolioText(data, "No hago anuncios. Creo recomendaciones.", "I don't make ads. I create recommendations.")}</h2>{hasText(data.bio) && <p>{data.bio}</p>}</div>{(data.contentTypes.length > 0 || hasAnyText(data.followers, data.monthlyViews, data.womenAudience)) && <div className="feedStoryPanel">{data.contentTypes.length > 0 && <><small>{portfolioText(data, "FORMATOS QUE DISFRUTO", "FORMATS I ENJOY")}</small><div className="feedFormats">{data.contentTypes.map((type) => <span key={type}>{portfolioOption(data, type)}</span>)}</div></>}{hasAnyText(data.followers, data.monthlyViews, data.womenAudience) && <div className="feedMicroMetrics">{hasText(data.followers) && <span><b>{data.followers}</b>{portfolioText(data, "seguidores", "followers")}</span>}{hasText(data.monthlyViews) && <span><b>{data.monthlyViews}</b>{portfolioText(data, "vistas / mes", "views / month")}</span>}{hasText(data.womenAudience) && <span><b>{data.womenAudience}</b>{portfolioText(data, "mujeres", "women")}</span>}</div>}</div>}</section>}
    {groups.length > 0 && <section className="feedLibrary feedSection">{groups.map((group) => <article className="feedLibraryGroup" key={group.category}><header><h3>{portfolioOption(data, group.category)}</h3><span>{String(group.items.length).padStart(2, "0")} {portfolioText(data, "PIEZAS", "PIECES")}</span></header><div className="feedLibraryRow" style={{ "--feed-count": Math.min(group.items.length, 4) } as CSSProperties}>{group.items.map((item) => <div className="feedLibraryMedia" key={item.id}><ExperienceMedia item={item} label={portfolioOption(data, group.category)} /></div>)}</div></article>)}</section>}
    {brands.length > 0 && <section className="feedBrands feedSection"><small className="feedKicker">{portfolioText(data, "HAN CONFIADO EN MI MIRADA", "THEY TRUSTED MY VISION")}</small><h2>{portfolioText(data, "Marcas con las que he creado.", "Brands I have created with.")}</h2><div className="feedBrandRail">{brands.map((brand) => <article key={brand.id}><img src={brand.url} alt={`${portfolioText(data, "Logo de", "Logo for")} ${brand.name}`} /><span>{brand.name}</span></article>)}</div></section>}
    {(data.services.length > 0 || hasText(data.womenAudience) || countries.length > 0) && <section className="feedCollab feedSection" id="feed-services">{data.services.length > 0 && <div><small className="feedKicker">{portfolioText(data, "TRABAJEMOS JUNTAS", "LET'S WORK TOGETHER")}</small><h2>{portfolioText(data, "Un menú de contenido hecho para tu marca.", "A content menu made for your brand.")}</h2><div className="feedServiceList">{data.services.map((service, index) => <div className="feedServiceRow" key={service}><span>{String(index + 1).padStart(2, "0")}</span><strong>{portfolioOption(data, service)}</strong><small>{servicePrice(data, service)}</small></div>)}</div></div>}{(hasText(data.womenAudience) || countries.length > 0) && <aside className="feedAudienceCard"><small>{portfolioText(data, "MI COMUNIDAD", "MY COMMUNITY")}</small><h3>{portfolioText(data, "Personas reales conectando con historias reales.", "Real people connecting with real stories.")}</h3>{hasText(data.womenAudience) && <div className="feedAudienceHero"><b>{data.womenAudience}</b><span>{portfolioText(data, "audiencia femenina", "female audience")}</span></div>}{countries.length > 0 && <div className="feedCountryList">{countries.map((country) => <p key={country}><span>{country}</span></p>)}</div>}</aside>}</section>}
    {hasAnyText(data.availability, data.whatsapp) && <section className="feedContact"><small className="feedKicker">{portfolioText(data, "¿TIENES UNA IDEA?", "HAVE AN IDEA?")}</small><h2>{portfolioText(data, "Hagamos contenido que no parezca publicidad.", "Let's make content that doesn't feel like an ad.")}</h2>{hasText(data.availability) && <p>{data.availability}</p>}{hasText(data.whatsapp) && <a className="feedContactButton" href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Empecemos un proyecto", "Let's start a project")} <span><Icon glyph="↗" /></span></a>}</section>}
    <footer className="feedFooter"><strong>{data.name} · UGC Creator</strong><span>{data.location}</span><span>{portfolioText(data, "Hecho para conectar.", "Made to connect.")}</span></footer>
  </div>;
}

export function PostcardJournalPortfolio({ data, media, brands, schema, expanded }: ExperienceProps) {
  const portrait = media.find((item) => item.category === "__portrait") ?? null;
  const work = visibleWork(data, media).slice(0, Math.max(6, schema.categoryLimit * 2));
  const countries = data.topCountries.split("·").map((item) => item.trim()).filter(Boolean);
  const cards = work.length ? work : [null, null, null, null, null, null];
  return <div className={`portfolioExperiencePage postcardJournal font-${data.fontStyle} ${expanded ? "expanded" : "compact"}`} style={{ "--experience-accent": portfolioAccent(data) } as CSSProperties}>
    <header className="pcNav"><a href="#pc-top"><b>{data.name}</b><span>FIELD NOTES / UGC</span></a><nav><a href="#pc-stops">{portfolioText(data, "Paradas", "Stops")}</a><a href="#pc-kit">{portfolioText(data, "Kit creativo", "Creative kit")}</a>{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Trabajemos ↗", "Let's work ↗")}</a>}</nav></header>
    <section className="pcHero" id="pc-top"><div className="pcHeroCopy">{hasText(data.location) && <span>{portfolioText(data, "DESPACHOS DESDE", "DISPATCHES FROM")} {data.location.toUpperCase()}</span>}<h1>{portfolioText(data, "Historias para marcas con ganas de viajar.", "Stories for brands ready to travel.")}</h1><p>{data.title}</p><div>{data.niches.map((niche) => <b key={niche}>{portfolioOption(data, niche)}</b>)}</div></div><div className="pcHeroPostcard"><div><ExperienceMedia item={portrait} label={portfolioText(data, "Retrato de creadora", "Creator portrait")} priority /></div><span className="pcStamp">UGC<br />AIR MAIL</span><small>{data.location}<br />{data.availability}</small></div></section>
    <div className="pcRoute">{[...data.niches, ...data.contentTypes].slice(0, 6).map((item, index) => <span key={`${item}-${index}`}><i>{index + 1}</i>{portfolioOption(data, item)}</span>)}</div>
    {(hasAnyText(data.creativeDiary, data.bio)) && <section className="pcIntro"><small>{portfolioText(data, "NOTA DE LA CREADORA", "CREATOR'S NOTE")}</small><h2>{portfolioText(data, "Recolecto momentos cotidianos y los convierto en lugares donde una marca quiere estar.", "I collect everyday moments and turn them into places where a brand wants to be.")}</h2><p>{data.creativeDiary || data.bio}</p></section>}
    {work.length > 0 && <section className="pcStops" id="pc-stops"><header><span>CAMERA ROLL / {String(cards.length).padStart(2, "0")}</span><h2>{portfolioText(data, "Paradas recientes.", "Recent stops.")}</h2>{hasText(data.campaignTitle) && <p>{data.campaignTitle}</p>}</header><div className="pcWall">{cards.map((item, index) => <article key={item?.id ?? `postcard-${index}`} className={`pcCard pcCard-${index % 4}`}><div><ExperienceMedia item={item} label={portfolioOption(data, item?.category ?? portfolioText(data, "Próxima parada", "Next stop"))} /></div><footer><span>{portfolioOption(data, item?.category ?? data.niches[index % Math.max(1, data.niches.length)] ?? "UGC")}</span><b>{portfolioOption(data, data.contentTypes[index % Math.max(1, data.contentTypes.length)] ?? "Story")}</b><i><Icon glyph="✦" /></i></footer></article>)}</div></section>}
    <section className="pcPassport" id="pc-kit"><div><small>{portfolioText(data, "PASAPORTE CREATIVO", "CREATIVE PASSPORT")}</small><h2>{portfolioText(data, "Lista para producir, grabar y entregar.", "Ready to produce, shoot and deliver.")}</h2><p>{portfolioOptions(data, data.includes).join(" · ")}</p></div><div className="pcServices">{data.services.map((service, index) => <article key={service}><span>0{index + 1}</span><strong>{portfolioOption(data, service)}</strong><b>{servicePrice(data, service)}</b></article>)}</div></section>
    {(hasAnyText(data.followers, data.monthlyViews) || countries.length > 0) && <section className="pcProof">{hasText(data.followers) && <div><small>COMUNIDAD EN RUTA</small><b>{data.followers}</b><span>seguidores</span></div>}{hasText(data.monthlyViews) && <div><small>VENTANA MENSUAL</small><b>{data.monthlyViews}</b><span>visualizaciones</span></div>}{countries.length > 0 && <div><small>DESTINOS PRINCIPALES</small>{countries.slice(0, 4).map((country) => <span key={country}>{country}</span>)}</div>}</section>}
    {brands.length > 0 && <section className="pcBrands"><span>{portfolioText(data, "SELLOS EN EL PASAPORTE", "STAMPS IN THE PASSPORT")}</span><div>{brands.map((brand) => <article key={brand.id}><img src={brand.url} alt={`${portfolioText(data, "Logo de", "Logo for")} ${brand.name}`} /><small>{brand.name}</small></article>)}</div></section>}
    {hasAnyText(data.email, data.instagram, data.whatsapp, data.location) && <section className="pcContact"><span>{portfolioText(data, "PRÓXIMO DESTINO", "NEXT DESTINATION")}</span><h2>{portfolioText(data, "Tu marca puede ser la siguiente historia.", "Your brand could be the next story.")}</h2>{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Reservemos la fecha", "Let's book the date")} <b><Icon glyph="→" /></b></a>}<footer>{hasText(data.instagram) && <a href={socialLink("instagram", data.instagram)} data-analytics-target="instagram">{data.instagram}</a>}{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{data.whatsapp}</a>}{hasText(data.location) && <b>{data.location}</b>}</footer></section>}
  </div>;
}

export function CampaignStoriesPortfolio({ data, media, brands, schema, expanded }: ExperienceProps) {
  const portrait = media.find((item) => item.category === "__portrait") ?? null;
  const groups = categoryGroups(data, media, schema);
  const cases = groups;
  return <div className={`portfolioExperiencePage campaignStories font-${data.fontStyle} ${expanded ? "expanded" : "compact"}`} style={{ "--experience-accent": portfolioAccent(data) } as CSSProperties}>
    <header className="csNav"><a href="#cs-top">{hasText(data.name) && <strong>{data.name}</strong>}<span>Creative portfolio</span></a><nav aria-label={portfolioText(data, "Secciones", "Sections")}>{cases.length > 0 && <a href="#cs-cases">{portfolioText(data, "Casos", "Cases")}</a>}{data.services.length > 0 && <a href="#cs-services">{portfolioText(data, "Servicios", "Services")}</a>}{hasText(data.whatsapp) && <a className="csContactLink" href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Trabajemos ↗", "Let's work ↗")}</a>}</nav></header>
    <section className="csHero" id="cs-top"><div className="csHeroCopy"><span className="csEdition">UGC · CREATIVE CASE FILES</span><h1>{portfolioText(data, "Ideas que se sienten. Estrategia que funciona.", "Ideas you can feel. Strategy that works.")}</h1>{hasText(data.bio) && <p>{data.bio}</p>}{hasAnyText(data.followers, data.monthlyViews, data.location) && <div className="csHeroMeta">{hasText(data.followers) && <span><b>{data.followers}</b> {portfolioText(data, "seguidores", "followers")}</span>}{hasText(data.monthlyViews) && <span><b>{data.monthlyViews}</b> {portfolioText(data, "vistas / mes", "views / month")}</span>}{hasText(data.location) && <span><b>{data.location}</b> {portfolioText(data, "base creativa", "creative base")}</span>}</div>}</div><div className="csPortrait"><ExperienceMedia item={portrait} label={portfolioText(data, "Retrato de creadora", "Creator portrait")} priority /><span>{portfolioText(data, "ESTRATEGIA + PRODUCCIÓN", "STRATEGY + PRODUCTION")}</span></div></section>
    {cases.length > 0 && <section className="csCases" id="cs-cases"><header className="csSectionIntro"><span>{portfolioText(data, "CASOS SELECCIONADOS", "SELECTED CASES")}</span>{hasText(data.campaignTitle) && <h2>{data.campaignTitle}</h2>}<p>{portfolioText(data, "Cada pieza parte de una idea clara y termina lista para conectar, convertir o construir confianza.", "Every piece starts with a clear idea and ends ready to connect, convert or build trust.")}</p></header>{cases.map((group, index) => {
      const story = data.caseStudies[group.category] ?? emptyCase;
      const mediaSlots = group.items.slice(0, 3);
      const brief = story.brief || data.bio;
      const hook = story.hook || data.campaignTitle;
      return <article className="csCase" key={group.category}><div className="csCaseNumber">CASE {String(index + 1).padStart(2, "0")}</div><div className="csCaseCopy"><small>{story.client || portfolioOption(data, group.category)}</small><h3>{portfolioOption(data, group.category)}</h3>{hasAnyText(brief, hook, story.result) && <dl>{hasText(brief) && <div><dt>{portfolioText(data, "EL BRIEF", "THE BRIEF")}</dt><dd>{brief}</dd></div>}{hasText(hook) && <div className="csHook"><dt>{portfolioText(data, "EL HOOK", "THE HOOK")}</dt><dd>“{hook}”</dd></div>}{hasText(story.result) && <div><dt>{portfolioText(data, "EL RESULTADO", "THE RESULT")}</dt><dd>{story.result}</dd></div>}</dl>}{hasText(story.testimonial) && <blockquote>“{story.testimonial}”{hasText(story.client) && <cite>— {story.client}</cite>}</blockquote>}</div><div className={`csCaseMedia count-${mediaSlots.length}`}>{mediaSlots.map((item, mediaIndex) => <ExperienceMedia key={item.id ?? `${group.category}-${mediaIndex}`} item={item} label={portfolioOption(data, group.category)} />)}</div></article>;
    })}</section>}
    {brands.length > 0 && <section className="csBrands"><span>{portfolioText(data, "EXPERIENCIA DE MARCA", "BRAND EXPERIENCE")}</span><div>{brands.map((brand) => <article key={brand.id}><img src={brand.url} alt={`${portfolioText(data, "Logo de", "Logo for")} ${brand.name}`} /><small>{brand.name}</small></article>)}</div></section>}
    {(data.includes.length > 0 || data.services.length > 0) && <section className="csServices" id="cs-services"><div><span>{portfolioText(data, "DEL CONCEPTO A LA ENTREGA", "FROM CONCEPT TO DELIVERY")}</span><h2>{portfolioText(data, "Contenido con intención en cada etapa.", "Purposeful content at every stage.")}</h2>{data.includes.length > 0 && <p>{portfolioOptions(data, data.includes).join(" · ")}</p>}</div>{data.services.length > 0 && <div className="csServiceList">{data.services.map((service, index) => <article key={service}><span>{String(index + 1).padStart(2, "0")}</span><strong>{portfolioOption(data, service)}</strong><small>{servicePrice(data, service)}</small></article>)}</div>}</section>}
    {hasAnyText(data.email, data.instagram, data.whatsapp) && <section className="csContact"><span>{portfolioText(data, "PRÓXIMO CASO", "NEXT CASE")}</span><h2>{portfolioText(data, "Hagamos una campaña que merezca ser contada.", "Let's make a campaign worth telling.")}</h2>{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Cuéntame sobre tu marca", "Tell me about your brand")} <b><Icon glyph="↗" /></b></a>}{hasAnyText(data.instagram, data.whatsapp) && <div>{hasText(data.instagram) && <a href={socialLink("instagram", data.instagram)} target="_blank" rel="noreferrer" data-analytics-target="instagram">{data.instagram}</a>}{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{data.whatsapp}</a>}</div>}</section>}
  </div>;
}

export function PersonalScrapbookPortfolio({ data, media, brands, schema, expanded }: ExperienceProps) {
  const portrait = media.find((item) => item.category === "__portrait") ?? null;
  const work = visibleWork(data, media).slice(0, schema.categoryLimit * 2);
  const collage = [portrait, work[0] ?? null, work[1] ?? null];
  const process = data.includes.slice(0, 3);
  return <div className={`portfolioExperiencePage personalScrapbook font-${data.fontStyle} ${expanded ? "expanded" : "compact"}`} style={{ "--experience-accent": portfolioAccent(data), "--chosen-accent": portfolioAccent(data) } as CSSProperties}>
    <header className="psNav"><a href="#ps-top">{data.name}<i><Icon glyph="♡" /></i></a><nav><a href="#ps-diary">{portfolioText(data, "Mi diario", "My diary")}</a><a href="#ps-work">{portfolioText(data, "Creaciones", "Creations")}</a>{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Trabajemos ↗", "Let's work ↗")}</a>}</nav></header>
    <section className="psHero" id="ps-top"><div className="psHeroCopy"><span>{portfolioText(data, "MI PEQUEÑO RINCÓN CREATIVO", "MY LITTLE CREATIVE CORNER")}</span><h1>{portfolioText(data, "Historias bonitas, momentos reales.", "Beautiful stories, real moments.")}</h1><p>{data.title}</p><div>{data.niches.map((niche) => <span key={niche}>#{portfolioOption(data, niche).toLowerCase()}</span>)}</div></div><div className="psHeroCollage">{collage.map((item, index) => <div className={`psPolaroid psPolaroid-${index + 1}`} key={item?.id ?? `ps-hero-${index}`}><i className="psTape" /><ExperienceMedia item={item} label={index === 0 ? portfolioText(data, "Esta soy yo", "This is me") : portfolioOption(data, item?.category ?? portfolioText(data, "Mi contenido", "My content"))} priority={index === 0} /><span>{index === 0 ? portfolioText(data, "hola, soy yo ✦", "hi, it's me ✦") : portfolioOption(data, item?.category ?? portfolioText(data, "próxima idea", "next idea"))}</span></div>)}<b className="psDoodle">create<br />with<br />feeling!</b></div></section>
    {(hasAnyText(data.availability, data.location, data.creativeDiary, data.bio) || process.length > 0) && <section className="psDiary" id="ps-diary">{hasAnyText(data.availability, data.location) && <aside><span>{portfolioText(data, "NOTA PARA LAS MARCAS", "A NOTE FOR BRANDS")}</span>{hasText(data.availability) && <b>{data.availability}</b>}{hasText(data.location) && <small>{data.location}</small>}</aside>}<div><small>{portfolioText(data, "ASÍ CREO CONTENIDO", "HOW I CREATE CONTENT")}</small><h2>{portfolioText(data, "Mi proceso comienza con una emoción, no con un anuncio.", "My process starts with an emotion, not an ad.")}</h2>{hasAnyText(data.creativeDiary, data.bio) && <p>{data.creativeDiary || data.bio}</p>}{process.length > 0 && <div className="psProcess">{process.map((item, index) => <span key={item}><b>0{index + 1}</b>{portfolioOption(data, item)}</span>)}</div>}</div></section>}
    {work.length > 0 && <section className="psWork" id="ps-work"><header><span>{portfolioText(data, "RECIÉN SALIDO DE MI CÁMARA", "FRESH FROM MY CAMERA")}</span><h2>{portfolioText(data, "Creaciones que guardaría en favoritos.", "Creations worth saving to favorites.")}</h2></header><div className="psWall">{work.map((item, index) => <article key={item.id}><i className="psTape" /><ExperienceMedia item={item} label={portfolioOption(data, item.category)} /><footer><span>{portfolioOption(data, item.category)}</span><b>{portfolioOption(data, data.contentTypes[index % Math.max(1, data.contentTypes.length)] ?? "UGC")}</b></footer></article>)}</div></section>}
    {(data.services.length > 0 || hasAnyText(data.followers, data.monthlyViews) || data.contentTypes.length > 0) && <section className="psNotes">{data.services.length > 0 && <div><span>{portfolioText(data, "LO QUE PUEDO CREAR", "WHAT I CAN CREATE")}</span><h2>{portfolioText(data, "Ideas listas para cobrar vida.", "Ideas ready to come to life.")}</h2>{data.services.map((service) => <p key={service}><Icon glyph="✦" /> {portfolioOption(data, service)}</p>)}</div>}{hasAnyText(data.followers, data.monthlyViews) && <aside><small>{portfolioText(data, "MI COMUNIDAD", "MY COMMUNITY")}</small>{hasText(data.followers) && <><strong>{data.followers}</strong><span>{portfolioText(data, "personas siguiendo la historia", "people following the story")}</span></>}{hasText(data.monthlyViews) && <b>{data.monthlyViews} {portfolioText(data, "vistas / mes", "views / month")}</b>}</aside>}{data.contentTypes.length > 0 && <div className="psFormats">{data.contentTypes.map((type) => <span key={type}>{portfolioOption(data, type)}</span>)}</div>}</section>}
    {brands.length > 0 && <section className="psBrands"><span>{portfolioText(data, "HE CREADO CON", "I HAVE CREATED WITH")}</span><div>{brands.map((brand) => <article key={brand.id}><img src={brand.url} alt={`${portfolioText(data, "Logo de", "Logo for")} ${brand.name}`} /><small>{brand.name}</small></article>)}</div></section>}
    {hasAnyText(data.email, data.whatsapp, data.instagram, data.tiktok) && <section className="psContact"><span>{portfolioText(data, "UNA ÚLTIMA NOTITA", "ONE LAST NOTE")}</span><h2>{portfolioText(data, "¿Creamos algo juntas?", "Shall we create something together?")}</h2><p>{portfolioText(data, "Cuéntame qué imaginas para tu marca. Yo pongo la cámara, las ideas y el cuidado en cada detalle.", "Tell me what you imagine for your brand. I'll bring the camera, the ideas and care for every detail.")}</p>{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Sí, trabajemos", "Yes, let's work")} <b><Icon glyph="♡" /></b></a>}{hasAnyText(data.instagram, data.tiktok) && <div>{hasText(data.instagram) && <a href={socialLink("instagram", data.instagram)} target="_blank" rel="noreferrer" data-analytics-target="instagram">Instagram · {data.instagram}</a>}{hasText(data.tiktok) && <a href={socialLink("tiktok", data.tiktok)} target="_blank" rel="noreferrer" data-analytics-target="tiktok">TikTok · {data.tiktok}</a>}</div>}</section>}
  </div>;
}

export function ShowreelFirstPortfolio({ data, media, brands, schema, expanded }: ExperienceProps) {
  const portrait = media.find((item) => item.category === "__portrait") ?? null;
  const work = visibleWork(data, media);
  // "Retrato principal" is the cover selected by the creator in every template.
  const heroItem = portrait ?? work.find((item) => item.type === "video") ?? work[0] ?? null;
  const groups = categoryGroups(data, media, schema);
  return <div className={`portfolioExperiencePage showreelFirst font-${data.fontStyle} ${expanded ? "expanded" : "compact"}`} style={{ "--experience-accent": portfolioAccent(data) } as CSSProperties}>
    {hasText(data.whatsapp) && <a className="srFloatingContact" href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Trabajemos", "Let's work")} <span><Icon glyph="↗" /></span></a>}
    <section className="srHero" id="sr-top"><div className="srHeroMedia"><ExperienceMedia item={heroItem} label={portfolioText(data, "Showreel principal", "Main showreel")} ambient /></div><header><strong>{data.name}</strong><nav><a href="#sr-work">Reel</a><a href="#sr-services">{portfolioText(data, "Servicios", "Services")}</a></nav></header><div className="srHeroCopy"><span>SHOWREEL · UGC CREATOR</span><h1>{data.name}</h1><p>{data.title}</p></div><div className="srNow"><i /> NOW PLAYING <span>{portfolioOption(data, heroItem?.category ?? portfolioText(data, "Tu mejor pieza", "Your best work"))}</span></div><a className="srScroll" href="#sr-work">{portfolioText(data, "Explorar ↓", "Explore ↓")}</a></section>
    {data.niches.length > 0 && <div className="srTicker">{Array.from({ length: 2 }, (_, repeat) => data.niches.map((item, index) => <span key={`${repeat}-${item}-${index}`}>{portfolioOption(data, item)} <b><Icon glyph="✦" /></b></span>))}</div>}
    {groups.length > 0 && <section className="srWork" id="sr-work"><header><small>{portfolioText(data, "SELECCIÓN DE TRABAJO", "SELECTED WORK")}</small><h2>{portfolioText(data, "Todo lo que necesitas ver.", "Everything you need to see.")}</h2></header>{groups.map((group, groupIndex) => <article className="srCategory" key={group.category}><div className="srCategoryTitle"><span>{String(groupIndex + 1).padStart(2, "0")}</span><h3>{portfolioOption(data, group.category)}</h3><small>{group.items.length} {portfolioText(data, "PIEZAS", "PIECES")}</small></div><div className="srReelRow" style={{ "--sr-count": group.items.length } as CSSProperties}>{group.items.map((item, index) => <div className="srReelCard" key={item.id}><ExperienceMedia item={item} label={portfolioOption(data, group.category)} /><span>{String(index + 1).padStart(2, "0")}</span><small>{portfolioOption(data, data.contentTypes[index % Math.max(1, data.contentTypes.length)] ?? "UGC")}</small></div>)}</div></article>)}</section>}
    {(hasAnyText(data.followers, data.monthlyViews, data.womenAudience) || brands.length > 0) && <section className="srProof">{hasText(data.followers) && <span><b>{data.followers}</b> {portfolioText(data, "seguidores", "followers")}</span>}{hasText(data.monthlyViews) && <span><b>{data.monthlyViews}</b> {portfolioText(data, "vistas mensuales", "monthly views")}</span>}{hasText(data.womenAudience) && <span><b>{data.womenAudience}</b> {portfolioText(data, "audiencia femenina", "female audience")}</span>}{brands.length > 0 && <span><b>{brands.length}</b> {portfolioText(data, "marcas", "brands")}</span>}</section>}
    {brands.length > 0 && <section className="srBrands"><small>SELECTED CLIENTS</small><div>{brands.map((brand) => <article key={brand.id}><img src={brand.url} alt={`Logo de ${brand.name}`} /></article>)}</div></section>}
    {(data.services.length > 0 || data.includes.length > 0) && <section className="srServices" id="sr-services"><header><small>{portfolioText(data, "SERVICIOS + TARIFAS", "SERVICES + RATES")}</small><h2>{portfolioText(data, "¿Qué creamos?", "What shall we create?")}</h2></header>{data.services.length > 0 && <div>{data.services.map((service, index) => <article key={service}><span>{String(index + 1).padStart(2, "0")}</span><h3>{portfolioOption(data, service)}</h3><b>{servicePrice(data, service)}</b></article>)}</div>}{data.includes.length > 0 && <p>{portfolioOptions(data, data.includes).join(" · ")}</p>}</section>}
    {hasAnyText(data.email, data.whatsapp, data.location, data.instagram, data.tiktok) && <section className="srContact"><span>{portfolioText(data, "FIN DEL REEL · INICIO DE ALGO NUEVO", "END OF REEL · START OF SOMETHING NEW")}</span><h2>{portfolioText(data, "Tu producto. Mi próxima historia.", "Your product. My next story.")}</h2>{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Trabajemos por WhatsApp", "Let's work on WhatsApp")} <Icon glyph="↗" /></a>}<footer>{hasText(data.location) && <span>{data.location}</span>}{hasText(data.instagram) && <a href={socialLink("instagram", data.instagram)} target="_blank" rel="noreferrer" data-analytics-target="instagram">{data.instagram}</a>}{hasText(data.tiktok) && <a href={socialLink("tiktok", data.tiktok)} target="_blank" rel="noreferrer" data-analytics-target="tiktok">{data.tiktok}</a>}</footer></section>}
  </div>;
}

export function TalentProfilePortfolio({ data, media, brands, schema, expanded }: ExperienceProps) {
  const portrait = media.find((item) => item.category === "__portrait") ?? null;
  const groups = categoryGroups(data, media, schema);
  const capabilities = Array.from(new Set([...data.contentTypes, ...data.services])).slice(0, 8);
  const countries = data.topCountries.split("·").map((item) => item.trim()).filter(Boolean);
  return <div className={`portfolioExperiencePage talentProfile font-${data.fontStyle} ${expanded ? "expanded" : "compact"}`} style={{ "--experience-accent": portfolioAccent(data) } as CSSProperties}>
    <header className="tpNav"><a href="#tp-top"><b>BRILLA / TALENT</b><span>UGC CREATOR PROFILE</span></a><nav>{groups.length > 0 && <a href="#tp-work">{portfolioText(data, "Trabajo", "Work")}</a>}<a href="#tp-rates">{portfolioText(data, "Tarifas", "Rates")}</a>{hasText(data.whatsapp) && <a className="tpNavContact" href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{portfolioText(data, "Trabajemos", "Let's work")}</a>}</nav></header>
    <section className="tpHero" id="tp-top"><div className="tpPortrait"><ExperienceMedia item={portrait} label={portfolioText(data, "Retrato profesional", "Professional portrait")} priority /><span>{initials(data.name)}</span></div><div className="tpIntro">{hasText(data.location) && <span>CREATOR PROFILE · {data.location}</span>}{hasText(data.name) && <h1>{data.name}</h1>}{hasText(data.title) && <p className="tpRole">{data.title}</p>}{hasText(data.bio) && <p className="tpBio">{data.bio}</p>}{hasAnyText(data.location, data.languages, data.availability) && <div className="tpFacts">{hasText(data.location) && <span><small>BASE</small><b>{data.location}</b></span>}{hasText(data.languages) && <span><small>{portfolioText(data, "IDIOMAS", "LANGUAGES")}</small><b>{data.languages}</b></span>}{hasText(data.availability) && <span><small>{portfolioText(data, "ESTADO", "STATUS")}</small><b>{data.availability}</b></span>}</div>}{data.niches.length > 0 && <div className="tpTags">{data.niches.map((niche) => <span key={niche}>{portfolioOption(data, niche)}</span>)}</div>}{hasAnyText(data.instagram, data.tiktok) && <div className="tpSocial">{hasText(data.instagram) && <a href={socialLink("instagram", data.instagram)} target="_blank" rel="noreferrer" data-analytics-target="instagram">Instagram <Icon glyph="↗" /></a>}{hasText(data.tiktok) && <a href={socialLink("tiktok", data.tiktok)} target="_blank" rel="noreferrer" data-analytics-target="tiktok">TikTok <Icon glyph="↗" /></a>}</div>}</div></section>
    {capabilities.length > 0 && <section className="tpCapabilities"><header><small>{portfolioText(data, "CAPACIDADES", "CAPABILITIES")}</small><h2>{portfolioText(data, "Formatos que puedo producir para tu marca.", "Formats I can produce for your brand.")}</h2></header><div>{capabilities.map((capability, index) => <article key={capability}><span>{String(index + 1).padStart(2, "0")}</span><strong>{portfolioOption(data, capability)}</strong>{data.clientTypes.length > 0 && <small>{portfolioOption(data, data.clientTypes[index % data.clientTypes.length])}</small>}</article>)}</div></section>}
    {groups.length > 0 && <section className="tpWork" id="tp-work"><header><small>{portfolioText(data, "PORTAFOLIO", "PORTFOLIO")}</small><h2>{portfolioText(data, "Trabajo seleccionado por capacidad.", "Selected work by capability.")}</h2>{hasText(data.campaignTitle) && <p>{data.campaignTitle}</p>}</header>{groups.map((group) => <article className="tpWorkGroup" key={group.category}><div><h3>{portfolioOption(data, group.category)}</h3><span>{String(group.items.length).padStart(2, "0")} {portfolioText(data, "piezas", "pieces")}</span></div><section>{group.items.map((item, index) => <div key={item.id}><ExperienceMedia item={item} label={portfolioOption(data, group.category)} /><small>{portfolioOption(data, data.contentTypes[index % Math.max(1, data.contentTypes.length)] ?? "UGC")}</small></div>)}</section></article>)}</section>}
    {brands.length > 0 && <section className="tpBrands"><small>{portfolioText(data, "MARCAS", "BRANDS")}</small><h2>{portfolioText(data, "Experiencia seleccionada.", "Selected experience.")}</h2><div>{brands.map((brand) => <article key={brand.id}><img src={brand.url} alt={`${portfolioText(data, "Logo de", "Logo for")} ${brand.name}`} /><span>{brand.name}</span></article>)}</div></section>}
    {(hasAnyText(data.followers, data.monthlyViews, data.womenAudience) || countries.length > 0 || hasAnyText(data.videoRate, data.collabRate, data.storyRate, data.storyPackRate, data.usageRate) || data.includes.length > 0) && <section className="tpCommercial" id="tp-rates">{(hasAnyText(data.followers, data.monthlyViews, data.womenAudience) || countries.length > 0) && <div className="tpMetrics"><small>{portfolioText(data, "AUDIENCIA", "AUDIENCE")}</small><h2>{portfolioText(data, "Alcance y comunidad.", "Reach and community.")}</h2>{hasAnyText(data.followers, data.monthlyViews, data.womenAudience) && <div>{hasText(data.followers) && <span><b>{data.followers}</b>{portfolioText(data, "Seguidores", "Followers")}</span>}{hasText(data.monthlyViews) && <span><b>{data.monthlyViews}</b>{portfolioText(data, "Vistas / mes", "Views / month")}</span>}{hasText(data.womenAudience) && <span><b>{data.womenAudience}</b>{portfolioText(data, "Mujeres", "Women")}</span>}</div>}{countries.length > 0 && <p>{countries.join(" · ")}</p>}</div>}{(hasAnyText(data.videoRate, data.collabRate, data.storyRate, data.storyPackRate, data.usageRate) || data.includes.length > 0) && <div className="tpRates"><small>{portfolioText(data, "TARIFAS BASE", "BASE RATES")}</small>{hasText(data.videoRate) && <div><span>Video UGC</span><b>{data.videoRate}</b></div>}{hasText(data.collabRate) && <div><span>{portfolioText(data, "Reel colaborativo", "Collaborative Reel")}</span><b>{data.collabRate}</b></div>}{hasText(data.storyRate) && <div><span>{portfolioText(data, "Historia con CTA", "Story with CTA")}</span><b>{data.storyRate}</b></div>}{hasText(data.storyPackRate) && <div><span>{portfolioText(data, "Pack de historias", "Story Pack")}</span><b>{data.storyPackRate}</b></div>}{hasText(data.usageRate) && <div><span>{portfolioText(data, "Derechos de pauta / mes", "Paid Usage Rights / month")}</span><b>{data.usageRate}</b></div>}{data.includes.length > 0 && <p>{portfolioText(data, "Incluye:", "Includes:")} {portfolioOptions(data, data.includes).join(" · ")}</p>}</div>}</section>}
    {hasAnyText(data.email, data.whatsapp) && <section className="tpContact"><div><span>BOOKING / COLLABORATIONS</span><h2>{portfolioText(data, "Disponible para tu próxima campaña.", "Available for your next campaign.")}</h2></div><div>{hasText(data.email) && <a href={emailLink(data.email)} data-analytics-target="email">{data.email} <Icon glyph="↗" /></a>}{hasText(data.whatsapp) && <a href={whatsappLink(data.whatsapp)} target="_blank" rel="noreferrer" data-analytics-target="whatsapp">{data.whatsapp}</a>}</div></section>}
    <footer className="tpFooter"><b>{data.name}</b><span>UGC Creator · {data.location}</span><span>{portfolioText(data, "Perfil presentado por Brilla", "Profile presented by Brilla")}</span></footer>
  </div>;
}
